"""V2 schema additions

Revision ID: a5c1de8c77cd
Revises: d5d9932f47f7
Create Date: 2026-03-11 01:41:53.911039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5c1de8c77cd'
down_revision: Union[str, Sequence[str], None] = 'd5d9932f47f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('staff_comment', sa.String(), nullable=True))
    op.add_column('users', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['client_id'], ['id'])
    op.add_column('workers', sa.Column('worker_id_code', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('bank_ifsc', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('bank_account_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_workers_worker_id_code'), 'workers', ['worker_id_code'], unique=False)
    op.drop_column('workers', 'bank_details')
    op.drop_column('workers', 'upi_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('upi_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('bank_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workers_worker_id_code'), table_name='workers')
    op.drop_column('workers', 'bank_account_name')
    op.drop_column('workers', 'bank_ifsc')
    op.drop_column('workers', 'bank_account_number')
    op.drop_column('workers', 'worker_id_code')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    op.drop_column('payment_requests', 'staff_comment')
    # ### end Alembic commands ###
