"""v6_add_performance_indexes

Revision ID: dc7854073a94
Revises: e5f3c9a2b789
Create Date: 2026-03-24 13:56:03.347724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7854073a94'
down_revision: Union[str, Sequence[str], None] = 'e5f3c9a2b789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_balance_logs_added_by_client_id'), 'balance_logs', ['added_by_client_id'], unique=False)
    op.create_index(op.f('ix_balance_logs_staff_id'), 'balance_logs', ['staff_id'], unique=False)
    op.create_index('ix_balancelog_client', 'balance_logs', ['added_by_client_id'], unique=False)
    op.create_index('ix_payment_client_status', 'payment_requests', ['client_id', 'status'], unique=False)
    op.create_index('ix_payment_completed_at', 'payment_requests', ['completed_at'], unique=False)
    op.create_index(op.f('ix_payment_requests_client_id'), 'payment_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_payment_requests_locked_by_staff_id'), 'payment_requests', ['locked_by_staff_id'], unique=False)
    op.create_index(op.f('ix_payment_requests_worker_id'), 'payment_requests', ['worker_id'], unique=False)
    op.create_index('ix_payment_staff_status', 'payment_requests', ['locked_by_staff_id', 'status'], unique=False)
    op.create_index('ix_payment_worker_status', 'payment_requests', ['worker_id', 'client_id', 'status'], unique=False)
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_index('ix_payment_worker_status', table_name='payment_requests')
    op.drop_index('ix_payment_staff_status', table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_worker_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_locked_by_staff_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_client_id'), table_name='payment_requests')
    op.drop_index('ix_payment_completed_at', table_name='payment_requests')
    op.drop_index('ix_payment_client_status', table_name='payment_requests')
    op.drop_index('ix_balancelog_client', table_name='balance_logs')
    op.drop_index(op.f('ix_balance_logs_staff_id'), table_name='balance_logs')
    op.drop_index(op.f('ix_balance_logs_added_by_client_id'), table_name='balance_logs')
    # ### end Alembic commands ###
